title: Tim FAVERJON
url: "https://timfaverjon.github.io/"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

favicon: true

nav:
  - name: "About"
    link: "/en/about"
    lang: "en"
  - name: "Research"
    link: "/en/research"
    lang: "en"
  - name: "Teaching"
    link: "/en/teaching"
    lang: "en"
  - name: "Resume"
    link: "/en/resume.pdf"
    lang: "en"
  - name: "Contact"
    link: "/en/contact"
    lang: "en"
  - name: "IC2S2"
    link: "en/research/IC2S2"
    lang: "fr"
  - name: "À propos"
    link: "/"
    lang: "fr"
  - name: "Recherche"
    link: "/fr/recherche"
    lang: "fr"
  - name: "Enseignement"
    link: "/fr/enseignement"
    lang: "fr"
  - name: "CV"
    link: "/fr/CV.pdf"
    lang: "fr"
  - name: "Contact"
    link: "/fr/contact"
    lang: "fr"
  - name: "IC2S2"
    link: "fr/recherche/IC2S2"
    lang: "fr"